steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - Dockerfile.web
      - -t
      - europe-west1-docker.pkg.dev/scienceq-prod/cloud-run-source-deploy/scienceq-web:latest
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - europe-west1-docker.pkg.dev/scienceq-prod/cloud-run-source-deploy/scienceq-web:latest

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - scienceq-web
      - --image=europe-west1-docker.pkg.dev/scienceq-prod/cloud-run-source-deploy/scienceq-web:latest
      - --region=europe-west1
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars=API_URL=https://scienceq-api-886463515307.europe-west1.run.app
      - --port=8080
      - --project=scienceq-prod
