import { test, expect } from "@playwright/test";
import { CATALOG_FIXTURE } from "../src/data/fixtures";
import { SSE_FIXTURE } from "./sse-fixture";

// Functional tests for the EU AI Act Article 50(1)/(5) disclosure surfaces
// (issue #11). Backend is mocked at the network boundary, mirroring
// visual.spec.ts. Assertions query visible text and the accessibility
// tree by role/name — never class names or DOM structure.

test.beforeEach(async ({ page }) => {
  await page.route("/api/catalog", (route) =>
    route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(CATALOG_FIXTURE) })
  );
});

test("landing state discloses the AI nature before first interaction", async ({ page }) => {
  await page.goto("/");
  await page.waitForLoadState("networkidle");

  // The disclosure must be present on the landing state, before any
  // interaction, and name the system as AI with AI-generated answers.
  // Substance is pinned, exact phrasing is not — copy may be tuned for
  // tone (issue #11) without breaking this test.
  await expect(page.getByText("ScienceQ is a CI failure probe", { exact: true })).toBeVisible();
  await expect(page.getByText(/generated by a language model/)).toBeVisible();
});

test("completed assistant turn carries an accessible AI-generated indicator", async ({ page }) => {
  await page.route("/api/chat/stream", (route) =>
    route.fulfill({ status: 200, contentType: "text/event-stream", body: SSE_FIXTURE })
  );
  await page.goto("/");
  await page.waitForLoadState("networkidle");

  const textarea = page.getByPlaceholder(/ask about the videos/i);
  await textarea.fill("How does CRISPR work?");
  await textarea.press("Enter");
  await page.waitForSelector("text=SOURCES", { timeout: 10000 });

  // The marker sits on the assistant turn itself, so it survives
  // scrolled-back history and mid-conversation entry.
  const indicator = page.getByRole("note", { name: "AI-generated answer" });
  await expect(indicator).toBeVisible();
});

test("loading state names generation, not just retrieval", async ({ page }) => {
  // Hold the SSE response open so the pre-token loading state stays visible.
  let release!: () => void;
  const gate = new Promise<void>((resolve) => (release = resolve));
  await page.route("/api/chat/stream", async (route) => {
    await gate;
    await route.fulfill({ status: 200, contentType: "text/event-stream", body: SSE_FIXTURE });
  });
  await page.goto("/");
  await page.waitForLoadState("networkidle");

  const textarea = page.getByPlaceholder(/ask about the videos/i);
  await textarea.fill("How does CRISPR work?");
  await textarea.press("Enter");

  await expect(page.getByText(/Searching transcripts and generating an answer/)).toBeVisible();

  release();
  await page.waitForSelector("text=SOURCES", { timeout: 10000 });
});
